#build
FROM node:23-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# run with ngnix
FROM nginx:stable-alpine

# Supprime la config par défaut de nginx
RUN rm -rf /usr/share/nginx/html/*

# Copie le build React dans nginx
COPY --from=build /app/build /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
