stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build-job:
  stage: build
  script:
    - echo "Check Docker version"
    - docker version
    - echo "Building Docker image..."
    - docker build -t pern-app ./backend
  tags:
    - local-runner

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd backend
    - npm install
    - npm test
  tags:
    - local-runner

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to Minikube..."
    - kubectl config use-context minikube
    - kubectl apply -f ./k8s/
  tags:
    - local-runner
