version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=taraji
      - DB_NAME=myapppern
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: myapp-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taraji
      POSTGRES_DB: myapppern
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
