FROM node:23-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
# ⬇️ Copy the wait-for-it script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 5000

CMD ["node", "index.js"]
